---
- name: install apache2 server in ubuntu server
  become: yes
  hosts: myserver
  vars:
     document_root: /var/www/html
     apache_server_name: ali.com
     allow_ips:
       - 192.168.1.1
       - 192.168.1.2
       - 192.168.1.3
       - 41.233.115.169
  tasks:
    - name: install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: apply apache configuration 
      ansible.builtin.template:
        src: apache.config.j2
        dest: /etc/apache2/sites-available/000-default.conf
        mode: '0644'
        owner: root
        group: root
      notify: restart apache 
    - name: enable apache site 
      ansible.builtin.command:
        cmd: a2ensite 000-default.conf
      notify: restart apache
    - name: start and enable
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
  handlers:
  - name: restart apache
    ansible.builtin.service:
      name: apache2
      state: restarted
